### ISSUE TITLE
Testing 1.2 Quickstart

### ISSUE THREAD

**Issue by Mjvolk3** [tttianhao/CLEAN#1]
1. There is not `data/pretained` directory. I recommend the `pretrained` folder and just dropping a `.gitkeep` in it.
    - Maybe this is unnecessary if the  point 2. is clarified.
2. When you download the data you get a folder `CLEAN_pretrained` which then needs to be renamed to `pretrained.` I think changing `CLEAN_pretrained` to `pretrained` will be the easiest since this is what the `src` is referencing.

**Comment by tttianhao** [comment]
Thanks, I've reworded README.
