### ISSUE TITLE
No such file or directory: './data/esm_data/WP_063460136.pt'

### ISSUE THREAD

**Issue by zas97** [tttianhao/CLEAN#10]
I've followed the installation steps but when running the python CLEAN_infer_fasta.py --fasta_data price command I get the following error:
`
FileNotFoundError: [Errno 2] No such file or directory: './data/esm_data/WP_063460136.pt'`

From what I checked WP_063460136 is the name of the first sequence in the fasta file.

What should I do?

**Comment by samarthgupta1011** [comment]
Typically, we have seen such errors when running on RAM < 12 GB.
