### ISSUE TITLE
Error when inference with p-value in CPU only mode

### ISSUE THREAD

**Issue by AxenArk** [tttianhao/CLEAN#12]
Prompts 

> "RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU."

when I tried to run infer_pvalue as suggested in the 2.2.1 section of README with a CPU only installation.

Fixed by change 
https://github.com/tttianhao/CLEAN/blob/0e5f244606f5d5d6f6c0998dccc7526566f69edd/app/src/CLEAN/infer.py#L28
to
 `            checkpoint = torch.load('./data/pretrained/'+ train_data +'.pth', map_location=device)`

The same changes may also be applied to codes listed below:
https://github.com/tttianhao/CLEAN/blob/0e5f244606f5d5d6f6c0998dccc7526566f69edd/app/src/CLEAN/infer.py#L33
https://github.com/tttianhao/CLEAN/blob/0e5f244606f5d5d6f6c0998dccc7526566f69edd/app/src/CLEAN/infer.py#L41
https://github.com/tttianhao/CLEAN/blob/0e5f244606f5d5d6f6c0998dccc7526566f69edd/app/src/CLEAN/infer.py#L43
https://github.com/tttianhao/CLEAN/blob/0e5f244606f5d5d6f6c0998dccc7526566f69edd/app/src/CLEAN/infer.py#L95

**Comment by tttianhao** [comment]
Thanks for posting this! I'll create a PR later to fix the issue!

**Comment by canallee** [comment]
@AxenArk  Infer.py is updated with the fix, thanks for bringing this up! Closing this issue for now.
