### ISSUE TITLE
Is there a threshold for relatively reliable prediction of pairwise distance

### ISSUE THREAD

**Issue by timeresistance1996** [tttianhao/CLEAN#23]
Thanks for your useful code！
I'm a bit confused whether there is a recommend threshold of pairwise distance in the result file under the condition that the prediction is relatively reliable？

**Comment by canallee** [comment]
Hi there is no recommendation on the threshold of pairwise distance, but we proposed using the Gaussian mixture model (GMM) to provide uncertainty quantification and details can be found in our paper supplementary and [gmm.py](https://github.com/tttianhao/CLEAN/blob/main/app/gmm.py).
