### ISSUE TITLE
non-deterministic behavior in inference

### ISSUE THREAD

**Issue by pagpires** [tttianhao/CLEAN#25]
https://github.com/tttianhao/CLEAN/blob/main/app/src/CLEAN/utils.py#L88 creates inputs for model and gets embeddings. However, `list(dict.keys())` can be non-deterministic (depending on python version) and therefore the output embeddings can mismatch the actual entries.  Please fix them and ensure that the paper was using the correct embeddings.

**Comment by canallee** [comment]
Hi, in the README for installing CLEAN locally, we use Python 3.10.4, and since after Python 3.6, [dictionaries are ordered](https://medium.com/junior-dev/python-dictionaries-are-ordered-now-but-how-and-why-5d5a40ee327f), the current code will guarantee embedding order.
