### ISSUE TITLE
how can I get Confidencel Level ?

### ISSUE THREAD

**Issue by zhangzhenhuajack** [tttianhao/CLEAN#27]
I see a confidencel level column from https://clean.frontend.mmli1.ncsa.illinois.edu/results/554b268ec1074df283bc0081cea971a9/1 result，
![image](https://github.com/tttianhao/CLEAN/assets/11462004/0d62fb6f-0b55-44ab-81e6-43a131487159)

what men confidencel level? and how get this column ?

**Comment by canallee** [comment]
Please check out the app/gmm.py file and our paper's mention of Gaussian mixture models. Comment if you have more questions.
