### ISSUE TITLE
Questions about querying unclassified proteins

### ISSUE THREAD

**Issue by kaden1670** [tttianhao/CLEAN#30]
Hi - I have a few questions about inferring EC number from unclassified proteins or those not found in uniprot/swissprot. Can I pass in all protein fastas from my data, or can I only pass in enzymes? In other words, has CLEAN been designed to not give results for proteins that are not enzymes? I also noticed that the "Enzyme IDs" in `split100.csv` all correspond to accession numbers. Can I make up a unique ID for each uncategorized protein, or does CLEAN only work on proteins found in UniProt. If so, would passing in KEGG accessions (or those from other databases) as the enzyme IDs work?

**Comment by canallee** [comment]
It is possible for CLEAN model architecture (and not the currently released checkpoints) to be applied to different label types. The current label type supported is the EC numbers, but it would take just some small efforts to accommodate other label types (such as GO annotations), and you would have to train a new CLEAN model with your new dataset and label type. For the second question, CLEAN doesn't actually use any of the ID information during training (only the sequence of the protein is used), and you are free to use any type of the enzyme ID you want, just be mindful of the input dataset file format.
