### ISSUE TITLE
How to filter the prediction results based on the pairwise distance between cluster center of  EC number? 

### ISSUE THREAD

**Issue by xylapple2013** [tttianhao/CLEAN#33]
How should I filter the prediction results based on the pairwise distance between the cluster center of a EC number? 
what is the cutoff value?

**Comment by canallee** [comment]
Hi, please refer to the infer_maxsep() and infer_pvalue(). infer_maxsep() is deterministic, and will calculate a cutoff value automatically and predict the enzyme functions, infer_pvalue() is tunable, and you can allow more predicted functions/enzyme by setting a larger p-value.

**Comment by ZhuLvs** [comment]
"I now need to execute the inference step, and my sequence is a randomly generated protein. I don't have any information related to EC.
Should I just follow the quick-start method for inference?
Do I also need to manually perform the embedding generation step and consider the p-value and max-separation options afterward?
Thank you for your response."
