### ISSUE TITLE
How to get embedding distance between the query protein and the CLEAN-predicted EC number

### ISSUE THREAD

**Issue by kaden1670** [tttianhao/CLEAN#34]
Hello, I am reaching out to follow up on issue #32, which was marked as closed. I was wondering if it might be possible to revisit the follow up question in that thread or get further clarification. I greatly appreciate your time and assistance in this matter.

Thank you!

**Comment by canallee** [comment]
Hi, in the actual implementation, the checkpoint is loaded through `checkpoint = torch.load('./data/pretrained/'+ train_data +'.pth')`, can you verify that `'./data/pretrained/'+ train_data +'.pth')` exists?

**Comment by kaden1670** [comment]
These are the contents of `CLEAN/app/data/pretrained` :
`100.pt  70.pt  gmm_ensumble.pkl  split100.pth  split70.pth`

So when passing in an input filename, there is no corresponding pth file.

**Comment by canallee** [comment]
You should be using train_data="split100", and not "split100.pth"
