### ISSUE TITLE
How to set parameters？

### ISSUE THREAD

**Issue by moonhuwaa** [tttianhao/CLEAN#37]
Hello, I have a few questions about parameter settings. I would like to know how your parameters are set, such as n_ Pos, n_ Neg, batch_ Size these parameters. Do I need to consider the sample size of categories in the dataset when setting parameters? If my dataset has 60 categories, with the highest sample size category containing 50000 samples and the lowest sample size category containing 20 samples, facing such a dataset, n_ Pos, n_ Neg, batch_ How should these parameters of size be set?

**Comment by canallee** [comment]
Hi please first use the default parameters in the the README, and then try to see if it works. CLEAN is especially suited for your case, where data is highly imbalanced. I would suggest using a larger n_Neg, but perhaps not larger than 60. For contrastive learning, it's usually better to use larger batches, but CLEAN is set such that in one gradient update, every cluster center is updated (there is a cluster center for each of the categories), so the default batch size in your case would be 60.

**Comment by moonhuwaa** [comment]
Thank you for your reply.
