### ISSUE TITLE
Annotating functions of proteins having more than 1022 amino acid residues

### ISSUE THREAD

**Issue by Sourdoc** [tttianhao/CLEAN#47]
Hi,
I tried using the web version (https://clean.platform.moleculemaker.org/configuration) for predicting ec numbers from protein sequences, but it is throwing an error whenever the protein sequence length is greater than 1022. I am planning to install the git hub package and am wondering if git hub package can predict function of those proteins that have sequence length greater than 1022.

Please let me know,

Thanks,
Sourav Dutta
<img width="781" alt="image" src="https://github.com/tttianhao/CLEAN/assets/170913603/7ece4357-965b-44a3-841a-72e01a7f48b1">

**Comment by canallee** [comment]
Hi, CLEAN uses ESM-1b's embedding, and ESM-1b's max_length is 1024, so the current version of CLEAN is limited by this sequence length...
