### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by ZhuLvs** [tttianhao/CLEAN#49]
"I now need to execute the inference step, and my sequence is a randomly generated protein. I don't have any information related to EC.
Should I just follow the quick-start method for inference?
Do I also need to manually perform the embedding generation step and consider the p-value and max-separation options afterward?
Thank you for your response."

**Comment by canallee** [comment]
Yes, the quick start inference would be a good idea for inference. Since CLEAN expects ESM-1b embeddings, you would need to re-compute each sequence's embedding.
