### ISSUE TITLE
Error during inferencing 

### ISSUE THREAD

**Issue by chiragmathur27** [tttianhao/CLEAN#50]
Hi , 
I wanted to ask if there are constraints on the input sequences , if any how to modify them , i am getting error saying 'esm_data/{lookup}.pt' not found

PS: All my sequenes are under 1024 length, still a lot of their embeddings are not there 
Hoping to here from you soon

**Comment by canallee** [comment]
Hi, can you verify if some of the embeddings in your csv file are successfully embedded? 

In general, you should check the following commands run successfully:

```
python

>>> from CLEAN.utils import *

>>> csv_to_fasta("data/yourdataset.csv", "data/yourdataset.fasta")

>>> retrive_esm1b_embedding("yourdataset")
```
