### ISSUE TITLE
Training results on 4-ec number

### ISSUE THREAD

**Issue by Thmoas-sketch** [tttianhao/CLEAN#51]
Hello, I want to inquire about which loss you used for the pretrained model weights. When I used the weight you provided, it was good, but when I re-trained the model following your steps, it did not show the same performance as the original one. I am pretty confused with it. Is anything I missed here? Really appreciate your suggestions.

**Comment by canallee** [comment]
Hi can you double-check if you have re-computed the files for inference, such as distance map and cluster center embeddings? The issue could also be linked to this issue #46 and #41. Please also refer to this [recent result](https://github.com/jsunn-y/CARE/) that replicated CLEAN on better formulated data splits.
