### ISSUE TITLE
There have a problem when we run the command "python CLEAN_infer_fasta.py --fasta_data price"

### ISSUE THREAD

**Issue by liaohu1231** [tttianhao/CLEAN#6]
Traceback (most recent call last):
  File "/share/database/CLEAN/CLEAN_infer_fasta.py", line 30, in <module>
    main()
  File "/share/database/CLEAN/CLEAN_infer_fasta.py", line 24, in main
    infer_maxsep(train_data, test_data, report_metrics=False, pretrained=True)
  File "/share/soft/miniconda3/envs/clean/lib/python3.10/site-packages/CLEAN-0.1-py3.10.egg/CLEAN/infer.py", line 92, in infer_maxsep
Exception: No pretrained weights for this training data

We have found pretrained dataset, can you provided a website to download it?

**Comment by tttianhao** [comment]
Hi, you can find download link of the pretrained weights in section 1.2. https://drive.google.com/file/d/1zrEU-HPNV3wp7wLAx4KnuiVyD794Oboj/view?usp=sharing

**Comment by liaohu1231** [comment]
Thank you very much, however, this link can not open in china.

**Comment by liaohu1231** [comment]
Can you submit it into other website like figshare?

**Comment by tttianhao** [comment]
Can you access OneDrive from China?

**Comment by liaohu1231** [comment]
Yes, we can access OneDrive in China

**Comment by tttianhao** [comment]
https://uillinoisedu-my.sharepoint.com/:u:/g/personal/tyu16_illinois_edu/EdKblKeYXqdLpISQV_H8esoBGloss3NbNyAQ8yxHCz2AhQ?e=49dGgP
